install:
- 'git clone https://github.com/git-ftp/git-ftp.git'
- 'cd git-ftp'
- 'git checkout 1.1.0'
- 'sudo make install'
script:
- 'git clone https://github.com/Flibio/TravisDeployTest.git'
- 'dir'
- 'cd TravisDeployTest'
- 'git ftp init --user ${FTP_USER} --passwd ${FTP_PASS} ftp://flibio.net:21/travis'